# .gitlab-ci.yml für automatische Weiterleitung
pages:
  stage: deploy
  script:
    - mkdir -p public
    - |
      cat > public/index.html <<EOF
      <!DOCTYPE html>
      <html>
      <head>
          <meta charset="utf-8">
          <title>NarcoCalc - Umgezogen zu GitHub</title>
          <meta http-equiv="refresh" content="5; url=https://github.com/IhrGitHubUsername/narcocalc">
          <style>
              body {
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
                  margin: 0;
                  background-color: #f5f5f5;
              }
              .container {
                  text-align: center;
                  padding: 2rem;
                  background: white;
                  border-radius: 8px;
                  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  max-width: 500px;
              }
              h1 { color: #333; }
              .icon { font-size: 3rem; margin-bottom: 1rem; }
              a {
                  color: #0366d6;
                  text-decoration: none;
                  font-weight: bold;
              }
              a:hover { text-decoration: underline; }
              .progress {
                  width: 100%;
                  height: 4px;
                  background: #e0e0e0;
                  border-radius: 2px;
                  margin-top: 2rem;
                  overflow: hidden;
              }
              .progress-bar {
                  height: 100%;
                  background: #0366d6;
                  animation: progress 5s linear;
              }
              @keyframes progress {
                  from { width: 0%; }
                  to { width: 100%; }
              }
          </style>
      </head>
      <body>
          <div class="container">
              <div class="icon">🚀</div>
              <h1>NarcoCalc ist umgezogen!</h1>
              <p>Dieses Projekt wird jetzt auf GitHub weiterentwickelt.</p>
              <p>Sie werden in 5 Sekunden automatisch weitergeleitet...</p>
              <p>Falls nicht, klicken Sie hier:</p>
              <p><a href="https://github.com/IhrGitHubUsername/narcocalc">
                  https://github.com/IhrGitHubUsername/narcocalc
              </a></p>
              <div class="progress">
                  <div class="progress-bar"></div>
              </div>
          </div>
      </body>
      </html>
      EOF
  artifacts:
    paths:
      - public
  only:
    - main